name: flutter_challenge
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  grpc: ^3.0.2
  protobuf: ^2.0.1
  hooks_riverpod: ^1.0.3
  shared:
    path: ../shared
  uuid: ^3.0.5
  responsive_builder: ^0.4.1
  auto_size_text: ^3.0.0
  google_fonts: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/